/* Welcome to the SQL mini project. You will carry out this project partly in
the PHPMyAdmin interface, and partly in Jupyter via a Python connection.

This is Tier 2 of the case study, which means that there'll be less guidance for you about how to setup
your local SQLite connection in PART 2 of the case study. This will make the case study more challenging for you: 
you might need to do some digging, aand revise the Working with Relational Databases in Python chapter in the previous resource.

Otherwise, the questions in the case study are exactly the same as with Tier 1. 

PART 1: PHPMyAdmin
You will complete questions 1-9 below in the PHPMyAdmin interface. 
Log in by pasting the following URL into your browser, and
using the following Username and Password:

URL: https://sql.springboard.com/
Username: student
Password: learn_sql@springboard

The data you need is in the "country_club" database. This database
contains 3 tables:
    i) the "Bookings" table,
    ii) the "Facilities" table, and
    iii) the "Members" table.

In this case study, you'll be asked a series of questions. You can
solve them using the platform, but for the final deliverable,
paste the code for each solution into this script, and upload it
to your GitHub.

Before starting with the questions, feel free to take your time,
exploring the data, and getting acquainted with the 3 tables. */


/* QUESTIONS 
/* Q1: Some of the facilities charge a fee to members, but some do not.
Write a SQL query to produce a list of the names of the facilities that do. */
SELECT *
FROM `Facilities`
WHERE membercost != 0.0
LIMIT 0 , 30


SQL result
Host: localhost
Database: country_club
Generation Time: Jan 18, 2021 at 09:15 AM
Generated by: phpMyAdmin 4.0.10deb1 / MySQL 5.5.43-0ubuntu0.14.04.1
SQL query: SELECT * FROM `Facilities` WHERE membercost != 0.0 ORDER BY `Facilities`.`initialoutlay` ASC LIMIT 0,30 ;
Rows: 5

facid	monthlymaintenance	name	membercost	guestcost	initialoutlay	
4	3000	Massage Room 1	9.9	80.0	4000
5	3000	Massage Room 2	9.9	80.0	4000
6	80	Squash Court	3.5	17.5	5000
1	200	Tennis Court 2	5.0	25.0	8000
0	200	Tennis Court 1	5.0	25.0	10000


/* Q2: How many facilities do not charge a fee to members? */
SELECT *
FROM `Facilities`
WHERE membercost = 0.0
LIMIT 0 , 30

Host: localhost
Database: country_club
Generation Time: Jan 18, 2021 at 09:16 AM
Generated by: phpMyAdmin 4.0.10deb1 / MySQL 5.5.43-0ubuntu0.14.04.1
SQL query: SELECT * FROM `Facilities` WHERE membercost = 0.0 ORDER BY `Facilities`.`initialoutlay` ASC LIMIT 0,30 ;
Rows: 4

facid	monthlymaintenance	name	membercost	guestcost	initialoutlay	
3	10	Table Tennis	0.0	5.0	320
8	15	Pool Table	0.0	5.0	400
7	15	Snooker Table	0.0	5.0	450
2	50	Badminton Court	0.0	15.5	4000



/* Q3: Write an SQL query to show a list of facilities that charge a fee to members,
where the fee is less than 20% of the facility's monthly maintenance cost.
Return the facid, facility name, member cost, and monthly maintenance of the
facilities in question. */
SELECT facid, name, membercost, monthlymaintenance
FROM Facilities
WHERE membercost < monthlymaintenance * 0.2
LIMIT 0 , 30

Host: localhost
Database: country_club
Generation Time: Jan 18, 2021 at 09:17 AM
Generated by: phpMyAdmin 4.0.10deb1 / MySQL 5.5.43-0ubuntu0.14.04.1
SQL query: SELECT facid, name, membercost, monthlymaintenance FROM Facilities WHERE membercost < monthlymaintenance * 0.2 LIMIT 0 , 30;
Rows: 9

facid	name	membercost	monthlymaintenance	
0	Tennis Court 1	5.0	200
1	Tennis Court 2	5.0	200
2	Badminton Court	0.0	50
3	Table Tennis	0.0	10
4	Massage Room 1	9.9	3000
5	Massage Room 2	9.9	3000
6	Squash Court	3.5	80
7	Snooker Table	0.0	15
8	Pool Table	0.0	15



/* Q4: Write an SQL query to retrieve the details of facilities with ID 1 and 5.
Try writing the query without using the OR operator. */
SELECT *
FROM `Facilities`
WHERE facid =1
OR facid =5
LIMIT 0 , 30

Host: localhost
Database: country_club
Generation Time: Jan 18, 2021 at 09:18 AM
Generated by: phpMyAdmin 4.0.10deb1 / MySQL 5.5.43-0ubuntu0.14.04.1
SQL query: SELECT * FROM `Facilities` WHERE facid =1 OR facid =5 ORDER BY `Facilities`.`initialoutlay` ASC LIMIT 0,30 ;
Rows: 2

facid	monthlymaintenance	name	membercost	guestcost	initialoutlay	
5	3000	Massage Room 2	9.9	80.0	4000
1	200	Tennis Court 2	5.0	25.0	8000



/* Q5: Produce a list of facilities, with each labelled as
'cheap' or 'expensive', depending on if their monthly maintenance cost is
more than $100. Return the name and monthly maintenance of the facilities
in question. */
SELECT name, monthlymaintenance,
CASE WHEN monthlymaintenance >100
THEN 'Expensive'
ELSE 'Cheap'
END AS
TYPE FROM Facilities
LIMIT 0 , 30

Host: localhost
Database: country_club
Generation Time: Jan 18, 2021 at 09:18 AM
Generated by: phpMyAdmin 4.0.10deb1 / MySQL 5.5.43-0ubuntu0.14.04.1
SQL query: SELECT name, monthlymaintenance, CASE WHEN monthlymaintenance >100 THEN 'Expensive' ELSE 'Cheap' END AS TYPE FROM Facilities LIMIT 0 , 30;
Rows: 9

 This table does not contain a unique column. Grid edit, checkbox, Edit, Copy and Delete features are not available.
name	monthlymaintenance	TYPE	
Tennis Court 1	200	Expensive
Tennis Court 2	200	Expensive
Badminton Court	50	Cheap
Table Tennis	10	Cheap
Massage Room 1	3000	Expensive
Massage Room 2	3000	Expensive
Squash Court	80	Cheap
Snooker Table	15	Cheap
Pool Table	15	Cheap



/* Q6: You'd like to get the first and last name of the last member(s)
who signed up. Try not to use the LIMIT clause for your solution. */
SELECT MAX( memid ) , surname, firstname
FROM Members

Host: localhost
Database: country_club
Generation Time: Jan 18, 2021 at 09:19 AM
Generated by: phpMyAdmin 4.0.10deb1 / MySQL 5.5.43-0ubuntu0.14.04.1
SQL query: SELECT MAX( memid ) , surname, firstname FROM Members;
Rows: 1

 This table does not contain a unique column. Grid edit, checkbox, Edit, Copy and Delete features are not available.
MAX( memid )	surname	firstname	
37



/* Q7: Produce a list of all members who have used a tennis court.
Include in your output the name of the court, and the name of the member
formatted as a single column. Ensure no duplicate data, and order by
the member name. */


Host: localhost
Database: country_club
Generation Time: Jan 18, 2021 at 09:20 AM
Generated by: phpMyAdmin 4.0.10deb1 / MySQL 5.5.43-0ubuntu0.14.04.1
SQL query: SELECT DISTINCT CONCAT( joined.firstname, ' ', joined.surname ) AS full_name, joined.fac_name FROM ( SELECT b.bookid, f.facid, f.name AS fac_name, m.memid, m.firstname, m.surname FROM Bookings b LEFT JOIN Facilities f ON b.facid = f.facid LEFT JOIN Members m ON m.memid = b.memid WHERE m.memid !=0 ) AS joined WHERE joined.fac_name LIKE "Tennis%" ORDER BY 1;
Rows: 44

 This table does not contain a unique column. Grid edit, checkbox, Edit, Copy and Delete features are not available.
full_name	fac_name	
Anne Baker	Tennis Court 1
Anne Baker	Tennis Court 2
Burton Tracy	Tennis Court 1
Burton Tracy	Tennis Court 2
Charles Owen	Tennis Court 1
Charles Owen	Tennis Court 2
Darren Smith	Tennis Court 2
David Farrell	Tennis Court 1
David Farrell	Tennis Court 2
David Jones	Tennis Court 1
David Jones	Tennis Court 2
David Pinker	Tennis Court 1
Douglas Jones	Tennis Court 1
Erica Crumpet	Tennis Court 1
Florence Bader	Tennis Court 1
Florence Bader	Tennis Court 2
Gerald Butters	Tennis Court 1
Gerald Butters	Tennis Court 2
Henrietta Rumney	Tennis Court 2
Jack Smith	Tennis Court 1
Jack Smith	Tennis Court 2
Janice Joplette	Tennis Court 1
Janice Joplette	Tennis Court 2
Jemima Farrell	Tennis Court 1
Jemima Farrell	Tennis Court 2
Joan Coplin	Tennis Court 1
John Hunt	Tennis Court 1
John Hunt	Tennis Court 2
Matthew Genting	Tennis Court 1
Millicent Purview	Tennis Court 2
Nancy Dare	Tennis Court 1
Nancy Dare	Tennis Court 2
Ponder Stibbons	Tennis Court 1
Ponder Stibbons	Tennis Court 2
Ramnaresh Sarwin	Tennis Court 1
Ramnaresh Sarwin	Tennis Court 2
Tim Boothe	Tennis Court 1
Tim Boothe	Tennis Court 2
Tim Rownam	Tennis Court 1
Tim Rownam	Tennis Court 2
Timothy Baker	Tennis Court 1
Timothy Baker	Tennis Court 2
Tracy Smith	Tennis Court 1
Tracy Smith	Tennis Court 2






/* Q8: Produce a list of bookings on the day of 2012-09-14 which
will cost the member (or guest) more than $30. Remember that guests have
different costs to members (the listed costs are per half-hour 'slot'), and
the guest user's ID is always 0. Include in your output the name of the
facility, the name of the member formatted as a single column, and the cost.
Order by descending cost, and do not use any subqueries. */


Host: localhost
Database: country_club
Generation Time: Jan 18, 2021 at 09:21 AM
Generated by: phpMyAdmin 4.0.10deb1 / MySQL 5.5.43-0ubuntu0.14.04.1
SQL query: SELECT f.name as facility_name, CONCAT(m.firstname, ' ', m.surname) as full_name, CASE WHEN b.memid = 0 THEN f.guestcost * slots WHEN b.memid != 0 THEN f.membercost * slots END as total_cost FROM Bookings b LEFT JOIN Facilities f ON b.facid = f.facid LEFT JOIN Members m ON b.memid = m.memid WHERE LEFT(b.starttime, 10) = '2012-09-14' AND CASE WHEN b.memid = 0 THEN f.guestcost * slots WHEN b.memid != 0 THEN f.membercost * slots END > 30 ORDER BY 3 DESC LIMIT 0, 30 ;
Rows: 12

 This table does not contain a unique column. Grid edit, checkbox, Edit, Copy and Delete features are not available.
facility_name	full_name	total_cost	
Massage Room 2	GUEST GUEST	320.0
Massage Room 1	GUEST GUEST	160.0
Massage Room 1	GUEST GUEST	160.0
Massage Room 1	GUEST GUEST	160.0
Tennis Court 2	GUEST GUEST	150.0
Tennis Court 1	GUEST GUEST	75.0
Tennis Court 1	GUEST GUEST	75.0
Tennis Court 2	GUEST GUEST	75.0
Squash Court	GUEST GUEST	70.0
Massage Room 1	Jemima Farrell	39.6
Squash Court	GUEST GUEST	35.0
Squash Court	GUEST GUEST	35.0





/* Q9: This time, produce the same result as in Q8, but using a subquery. */

SELECT fac_name, full_name, total_cost
FROM (

SELECT f.name AS fac_name, CONCAT( m.firstname, ' ', m.surname ) AS full_name,
CASE WHEN b.memid =0
THEN f.guestcost * b.slots
WHEN b.memid !=0
THEN f.membercost * b.slots
END AS total_cost
FROM Bookings b
LEFT JOIN Facilities f ON b.facid = f.facid
LEFT JOIN Members m ON m.memid = b.memid
WHERE LEFT( b.starttime, 10 ) = '2012-09-14'
) AS joined
WHERE total_cost >30
ORDER BY 3 DESC

Host: localhost
Database: country_club
Generation Time: Jan 18, 2021 at 09:22 AM
Generated by: phpMyAdmin 4.0.10deb1 / MySQL 5.5.43-0ubuntu0.14.04.1
SQL query: SELECT fac_name, full_name, total_cost FROM ( SELECT f.name AS fac_name, CONCAT(m.firstname, ' ', m.surname) as full_name, CASE WHEN b.memid = 0 THEN f.guestcost * b.slots WHEN b.memid != 0 THEN f.membercost * b.slots END as total_cost FROM Bookings b LEFT JOIN Facilities f ON b.facid = f.facid LEFT JOIN Members m ON m.memid = b.memid WHERE LEFT(b.starttime, 10) = '2012-09-14' ) AS joined WHERE total_cost > 30 ORDER BY 3 DESC;
Rows: 12

 This table does not contain a unique column. Grid edit, checkbox, Edit, Copy and Delete features are not available.
fac_name	full_name	total_cost	
Massage Room 2	GUEST GUEST	320.0
Massage Room 1	GUEST GUEST	160.0
Massage Room 1	GUEST GUEST	160.0
Massage Room 1	GUEST GUEST	160.0
Tennis Court 2	GUEST GUEST	150.0
Tennis Court 2	GUEST GUEST	75.0
Tennis Court 1	GUEST GUEST	75.0
Tennis Court 1	GUEST GUEST	75.0
Squash Court	GUEST GUEST	70.0
Massage Room 1	Jemima Farrell	39.6
Squash Court	GUEST GUEST	35.0
Squash Court	GUEST GUEST	35.0



/* PART 2: SQLite

Export the country club data from PHPMyAdmin, and connect to a local SQLite instance from Jupyter notebook 
for the following questions.  

QUESTIONS:
/* Q10: Produce a list of facilities with a total revenue less than 1000.
The output of facility name and total revenue, sorted by revenue. Remember
that there's a different cost for guests and members! */

/* Q10: Produce a list of facilities with a total revenue less than 1000.
The output of facility name and total revenue, sorted by revenue. Remember
that there's a different cost for guests and members! */

SELECT fac_name, SUM(total_cost) as revenue
	    
FROM (
SELECT f.name AS fac_name,
       CASE WHEN b.memid = 0 THEN f.guestcost * b.slots  
            WHEN b.memid != 0 THEN f.membercost * b.slots END as total_cost 
FROM Bookings b
LEFT JOIN Facilities f ON b.facid = f.facid
LEFT JOIN Members m ON m.memid = b.memid
) AS joined
GROUP BY 1
HAVING revenue < 1000 
ORDER BY 2 DESC 


Host: localhost
Database: country_club
Generation Time: Jan 18, 2021 at 09:23 AM
Generated by: phpMyAdmin 4.0.10deb1 / MySQL 5.5.43-0ubuntu0.14.04.1
SQL query: /* Q10: Produce a list of facilities with a total revenue less than 1000. The output of facility name and total revenue, sorted by revenue. Remember that there's a different cost for guests and members! */ SELECT fac_name, SUM(total_cost) as revenue FROM ( SELECT f.name AS fac_name, CASE WHEN b.memid = 0 THEN f.guestcost * b.slots WHEN b.memid != 0 THEN f.membercost * b.slots END as total_cost FROM Bookings b LEFT JOIN Facilities f ON b.facid = f.facid LEFT JOIN Members m ON m.memid = b.memid ) AS joined GROUP BY 1 HAVING revenue < 1000 ORDER BY 2 DESC ;
Rows: 3

 This table does not contain a unique column. Grid edit, checkbox, Edit, Copy and Delete features are not available.
fac_name	revenue	
Pool Table	270.0
Snooker Table	240.0
Table Tennis	180.0




/* Q11: Produce a report of members and who recommended them in alphabetic surname,firstname order */


/* Q12: Find the facilities with their usage by member, but not guests */


/* Q13: Find the facilities usage by month, but not guests */

